channels:
  - conda-forge
  - nodefaults
dependencies:
  - mne
  - h5py
  - ruff
  - ipython
  - pip
  - pymc>=5
  - arviz
  - matplotlib>=3.5
  - pandas
  - fooof
  - seaborn
  - joblib
  - numpyro
  - pip:
      - plus_slurm
      - obob_mne
      - -e file:///mnt/obob/staff/fschmidt/git/fooof/
      - pymatreader