name: documentation

on: [push, pull_request, workflow_dispatch]
   branches:
      - main 
      
permissions:
  contents: write

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: latest
          cache: true
          locked: false
          frozen: false
          environments: doc
      - run: pixi run -e doc build_docs
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/build/html
          publish_branch: 'gh-pages'
          force_orphan: 'false'